---
title: "Clark County Tables"
output: pdf_document
header-includes:
    - \usepackage{caption}
---

\captionsetup[table]{labelformat=empty}

```{r import_packages, include=FALSE}
library(data.table)
library(janitor)
library(kableExtra)
library(knitr)
library(readxl)
library(tidyverse)
options(scipen = 999)
```

## Read in excel file

```{r read_data}
## Import
files <- list.files(pattern = "Revised2*", path = "data_raw/", 
                    recursive = TRUE, full.names = TRUE)
raw.data <- read_excel(files, .name_repair = "universal")
```

## Create the table lists

```{r create_tables}
source("R/create_tables.R")

```

```{r}
names_spaced <- c(linebreak(c("Reach", "Area", "Canopy Cover 2013 (Acres, % of unit cover)",
                            "Value\n(Number)", "Value\n(Number)", "Value\n(Number)",
                            "Value\n(Number)", "Value\n(Number)", "Value\n(Number)",
                            "Value\n(Number)"), align = "c"))
```



```{r render_table1}

RenderTable1 <- function(table.list, filename) {
  for (i in 1:length(table.list)) {
    print(kable(table.list[[i]],
                caption = paste0(names(table.list[i]),
                                 " Watershed and Reaches", sep = " "),
                format = "latex",
                align = "l",
                booktabs = TRUE,
                longtable = FALSE,
                linesep = "",
                col.names = linebreak(c("Reach", "Area", "Canopy Cover 2013 (Acres, % of unit cover)",
                            "Canopy Cover 2019 (Acres, % of unit cover)", 
                            "Change in canopy cover, 2013-2019 (Acres, % of unit cover) ",
                            "Permitted shoreline clearing in SMA, 2012-2022 (Acres)",
                            "Permitted shoreline compensatory mitigation 2012-2022 (Acres, % of change)",
                            "Permitted shoreline restoration 2019-2022 (Acres, % of change)", 
                            "Permitted clearing from DNR forestry permits, 2013-2021 (Acres)",
                            "Change in canopy cover not accounted for by issued SMA permits and/or DNR clearing (Acres, % of change)"), align = "c")) %>%
            kableExtra::kable_styling(
              position = "left",
              latex_options = c("striped", "scale_down"),
              stripe_color = "gray!15",
              full_width = FALSE,
              font_size = 160) %>%
            row_spec(row = 0, background = "#048CBD", color = "white") %>%
            column_spec(1:10, width = "50cm") %>%
            add_header_above(c("Change in Tree Canopy and Supporting Metrics" = 10),
                   bold = TRUE, font_size = 225) %>%
            save_kable(., paste("figures/", names(table.list[i]), filename, ".pdf", sep = ""), 
                       keep_tex = FALSE)) 
    cat("\n")
  }
}

```


```{r render_tables_function}

RenderTable2 <- function(table.list, filename) {
  for (i in 1:length(table.list)) {
    print(kable(table.list[[i]],
                caption = paste0(names(table.list[i]),
                                 " Watershed and Reaches", sep = " "),
                format = "latex",
                align = "l",
                booktabs = TRUE,
                longtable = FALSE,
                linesep = "",
                col.names = linebreak(c("Reach", "Area", "Impervious Cover 2013 (Acres, % of total unit)",
                            "Impervious Cover 2019 (Acres, % of total unit)", 
                            "Change in Impervious cover, 2013-2019 (Acres, % of unit cover)",
                            "Permitted impervious surface in SMA, 2012-2022 (Acres)",
                            "Permitted over-water structures in SMA, 2012-2022 (Acres) ",
                            "Permitted shoreline compensatory mitigation 2012-2022 (Acres, % of change)", 
                            "Permitted shoreline restoration 2019-2022 (Acres, % of change)",
                            "Change in impervious cover not accounted for by issued SMA permits (Acres, % of change)"), align = "c")) %>%
            kableExtra::kable_styling(
              position = "left",
              latex_options = c("striped", "scale_down"),
              stripe_color = "gray!15",
              full_width = FALSE,
              font_size = 160) %>%
            row_spec(row = 0, background = "#048CBD", color = "white") %>%
            column_spec(1:10, width = "50cm") %>%
            add_header_above(c("Change in Impervious Surface Cover and Supporting Metrics" = 10),
                   bold = TRUE, font_size = 225) %>%
            save_kable(., paste("figures/", names(table.list[i]), filename, ".pdf", sep = ""), 
                       keep_tex = FALSE)) 
    cat("\n")
  }
}

```


\captionsetup[table]{labelformat=empty}
```{r render_table2}
export.table1 <- lapply(export.table1, function(x) { x["Watershed"] <- NULL; x })
export.table2 <- lapply(export.table2, function(x) { x["Watershed"] <- NULL; x })


RenderTable1(export.table1, 
             filename = "Canopy")
RenderTable2(export.table2,
             filename = "Impervious")
```

```{r}

t <- export.table1[[1]]
t.table <- t %>%
  knitr::kable(
    caption = paste(names(export.table1[1]), "Watershed and Reaches", sep = " "),
    format = "latex",
    align = "l",
    booktabs = TRUE,
    longtable = FALSE,
    linesep = "",
    col.names = linebreak(c("Reach", "Area", "Canopy Cover 2013 (Acres, % of unit cover)",
                            "Canopy Cover 2019 (Acres, % of unit cover)", "Value\n(Number)", "Value\n(Number)",
                            "Value\n(Number)", "Value\n(Number)", "Value\n(Number)",
                            "Value\n(Number)"), align = "c")) %>%
  add_header_above(c("Change in Tree Canopy and Supporting Metrics" = 10),
                   bold = TRUE) %>%
  kableExtra::kable_styling(
      position = "left",
      latex_options = c("striped", "repeat_header", "scale_down"),
      stripe_color = "gray!15",
      full_width = FALSE) %>%
  row_spec(row = 0, background = "#048CBD", color = "white") %>%
  column_spec(1:10, width = "2cm")
save_kable(t.table, "figures/TEST.pdf", keep_tex = FALSE)

```